language: node_js
script:
- npm run test
- npm run build
notifications:
  email:
    on_success: change
    on_failure: change
  slack:
    rooms:
      secure: XbYa01h4/qPBhMYgxxiyhhHmSt6KUSQWlyFBiolu+cfgC5xf+5q9qE0ygljlk5RrWjJopGD5jNpEOZoEvG/ifu+YzIb7Xc0AINtM8i9AfRTFTX8oKokkbIxOhjd6nDVgNNCDliVpudHnbuXKWnJPyZJb9fINiwvecuFS2bO1DrzFt3FgRbka5SVejZLfomwW0g+6ddtlJFPa1Bwjh8wkI6naIRFYW722tqRAK7QeJWpFibxSiS21sb8mDP50+MdzSm+tt6Zna1z9LLsQjr+VMnLpeyJnDoCvS7dMCZm8bcrvNXAo4m5rMSx5in0wALIFvZKo8U9SIyHKGMRoxQNo3KO4qdCSR1GLZx/NAt9caFOFjPLQQztMKYzV9+KMz1nS4uzRoHjs8qqoJ/n/pGMIghVETaxtIcqwML6MAsgxIW4wTA5ZVRd7Mz8Vxc5dLAfkCDlBhPlDjQ+kWgZF5YgwZxwV2IlMR46OsJKPh5Ew0KoFKvgyrONh520tkI1+nKjjq+fr3bEwH6fm09jSqytWxCLvsKczkfFQeNvvwweMRh8hG1Z8AFEm/9ZjOiEtyWYBoTpaJYJk4M4mPmYo0xu2w2QUVSk7mlkuKsMQbIJPbkIhen7anQ25v/XX+yWPK551/kMSV/PtuUzAVQaJ/vUjCca1R/DHPQpUS19gU/axKnc=
cache:
  yarn: true
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: LdmOT1amSjtw5gRspMoYoNlf0dqHnS1ccC+cVvzrhPwibrfNW4SkSQ2AiwkDatNeYF9inrLnYRLmgtBzI3mkE8ccbtVlR6Qwg6WfihwM0l2q09Ks3yFQVSjfPdW3FZ4XhDXzE7243fjCPlEsxedJgjqU/24Ggn2GLe7PV74kiTbPvf4qQftNl/rw4FYP9XqJPfzv59QQovnog2ppgOg+E+3XIpNop6KOoEkkRup3rHsw5n1OjYHxkzRnqiigpVwwZ5dxUUnCUoEMwxvKaLguhsXVmm658DHehLGR0+F3MqesXMQrfP+LP3zopC18qhtRWoVrhbr+TSkF/5ipzFb9KtsWF4LhXX5+O791wTi8DpEE3MUZuxjPg+O90i2SxzsOjam9j/tF2f0IhAEX5j6rAWsUDnuJzvVwlqV4z7oQePFJmrXusJ79XkBOOSi6xc5huMq71cZVb8FUbDHzPFdQB9+uMpFwWphD/kEWwa8U2bVijXUWQhLtrDRY0HRhiZoqfPt6e8dH5A1EzOSe88dwFzbn1FvtN33NdztbKDf1Bb23iA2zUTKfUXQD/4crtPxRxTMhEGjBWyNhNn+u9Ywm5e/ILAv3DCJD1fd8UlgyynjjyTKui6sv9lyDkir3hCQBO1syulQJrxBZvJFbLt22weu3BDGC7DFE6/zgj8o3uoY=
  app: rd-shiny-invention
  on: stable
