language: node_js
script:
- npm run test
- npm run build
notifications:
  email:
    on_success: never
    on_failure: never
  slack:
    rooms:
      secure: QsVClVkbes4yWsVRRHZW+v1SEMle6rl24GCMQ5wEmifzbiMUn4dcZWTrMpNa31j4Y2Ne17G7odgzVaoQDbniQU097rI/bb8lQpuROhBa4w/4ekdF8svowsvR/o0k6Yu+Pgf4Sz7pAHBtRm+D2vqhchGKCLfwpydh7oJ+S42icPyOn+1kw11MJm/1nTOL5SGjUMWECBLR0q2xTmyt3kR9hvglpdLuvwYbKXd0e9xYnyruGB4+P7qDnzGLx+YnlGtgVQtE19NSCv3YAl0o3HEBgO6/kN5+NMKXMYyVFAMAci5zY2lXcdRHIr227SWGkiDk/vnqQ7W5aIooYmxlOtcvbWIlVfTCAgzwRC0fCYtk4g9p21lWKoY3e2t3qmX8dSyY5uXFehcamvrfXeciaZOqT524/RvqoG4U0iZjY+w8gj7OEqIh00CMgr6/LsnlRymBtdAJqS49yxmvzreRlbI+l8PlIAeut04lO6kcsxsHJZtrm2fvCuT9NAEXjUeSELdNZRSm6HA2vUwTKZz+tiE/hYA7pfzCMAnqgUFIvijuho95TZbQXnsArKBuY319PFeZ1xOv4qPEwTeG8CoQrE+Cp45AogTlxHt89DxtxqVXrtSK1nbfqz3D8aGOI5554X1hDlGO442rfKy6CuZwwM958HMStKcEC5Tg1/oNY9Ryu4I=
    on_success: change
    on_failure: always
cache:
  yarn: true
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: LdmOT1amSjtw5gRspMoYoNlf0dqHnS1ccC+cVvzrhPwibrfNW4SkSQ2AiwkDatNeYF9inrLnYRLmgtBzI3mkE8ccbtVlR6Qwg6WfihwM0l2q09Ks3yFQVSjfPdW3FZ4XhDXzE7243fjCPlEsxedJgjqU/24Ggn2GLe7PV74kiTbPvf4qQftNl/rw4FYP9XqJPfzv59QQovnog2ppgOg+E+3XIpNop6KOoEkkRup3rHsw5n1OjYHxkzRnqiigpVwwZ5dxUUnCUoEMwxvKaLguhsXVmm658DHehLGR0+F3MqesXMQrfP+LP3zopC18qhtRWoVrhbr+TSkF/5ipzFb9KtsWF4LhXX5+O791wTi8DpEE3MUZuxjPg+O90i2SxzsOjam9j/tF2f0IhAEX5j6rAWsUDnuJzvVwlqV4z7oQePFJmrXusJ79XkBOOSi6xc5huMq71cZVb8FUbDHzPFdQB9+uMpFwWphD/kEWwa8U2bVijXUWQhLtrDRY0HRhiZoqfPt6e8dH5A1EzOSe88dwFzbn1FvtN33NdztbKDf1Bb23iA2zUTKfUXQD/4crtPxRxTMhEGjBWyNhNn+u9Ywm5e/ILAv3DCJD1fd8UlgyynjjyTKui6sv9lyDkir3hCQBO1syulQJrxBZvJFbLt22weu3BDGC7DFE6/zgj8o3uoY=
  app: rd-shiny-invention
  on: stable
